### ISSUE TITLE
Feature Request: Allow multiple amounts/accounts to be specified on send

### ISSUE THREAD

**Issue by gregscullard** [Hashgraph-Exchange/HEX-PROVIDER#1]
Currently send looks like this
```
window.hex.sendHbar({
    amount: "20",
    transferTo: 0.0.XXXXXX
});
```

It would be really useful to be able to specify `amounts` and `transferTo` as arrays such as

```
window.hex.sendHbar({
    amounts: ["20", "30", "40"]
    transferTo: ["0.0.XXXXXX", "0.0.YYYYYY", "0.0.ZZZZZZ"]
});
```

or, even allowing tokens and hbar to be mixed in a `send` operation

```
window.hex.send({
  "hbar": [
    {
      "amount": 20,
      "to": "0.0.XXXXXX"
    },
    {
      "amount": 30,
      "to": "0.0.YYYYYY"
    },
    {
      "amount": 40,
      "to": "0.0.ZZZZZZ"
    }
  ],
  "tokens": [
    {
      "tokenId": "0.0.ABCDEFG",
      "amount": 40,
      "to": "0.0.ZZZZZZ"
    },
    {
      "tokenId": "0.0.PQRSTU",
      "amount": 40,
      "to": "0.0.YYYYYY"
    }
  ]
});
```

The extension when generating the transaction would add up the `amounts` and ensure a negative equivalent is add to the transfer and token lists accordingly.

This would allow for much more complex use cases to be supported by the extension.

**Comment by xavierpraveen** [comment]
@gregscullard Completed this feature and it is available in the latest release.

![image](https://user-images.githubusercontent.com/48013701/124917010-f20d7980-e010-11eb-8b5f-a938a6001fd9.png)
