### ISSUE TITLE
Feature Request: Allow arbirtray

### ISSUE THREAD

**Issue by gregscullard** [Hashgraph-Exchange/HEX-PROVIDER#2]
A browser client using the Java SDK is able to create an arbitrary transaction, it should be possible to send this (HEX encoded for example) to the extension so that the extension can display the transaction to be signed and upon approval from the user, sign and submit to Hedera.

This may require the extension to enable the browser access to the `Account Id` from the extension in order to create a complete transaction, including the transaction id.

Further, it may be beneficial for the extension to return the signed transaction (or signature alone) so that the client can manage the submission if so desired.

It could also be used to sign arbitrary data (a message for example) using the extension's account id's private key. This data may not always be a transaction is could be "a red fox is in the field".

**Comment by xavierpraveen** [comment]
@gregscullard This feature is completed and is now available in the latest release.

![image](https://user-images.githubusercontent.com/48013701/124917551-998aac00-e011-11eb-8ea1-431f8950d73d.png)
